services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: mp-app
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      # O host do DB é o serviço "postgres" (mesma rede do compose)
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    depends_on:
      - postgres
    expose:
      - "3000"           # expõe só na rede interna; Caddy atende 80/443
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webnet

  postgres:
    image: postgres:15
    container_name: mp-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - webnet

  caddy:
    image: caddy:2
    container_name: mp-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - webnet

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  webnet:
    driver: bridge
