services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev         # <<--- trocar para PROD quando for subir
    container_name: mp-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env
    command: sh -c "npm ci && npm run dev"

  postgres:
    image: postgres:15
    container_name: mp-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
